## 슬라이싱 (slicing)
* 배열[a:b:c]를 이용하여 배열의 일부를 잘라 표시할 수 있음
* a는 시작값, b는 끝값, c는 간격을 의미함
* index는 0 ~ len-1까지 존재하며, 아무것도 입력하지 않고 :로 사용할 경우, 모든 행 또는 열을 의미함
* :n으로 사용할 경우 0 ~ n-1 까지의 요소를 의미하며 n:으로 사용할 경우, n ~ len-1까지의 요소를 의미함
* -1을 입력할 경우, 마지막 index-1를 의미함

In [25]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a, a[:])
print(a[3:])
print(a[1:-1]) 
print(a[0:3:2])

[1 2 3 4 5] [1 2 3 4 5]
[4 5]
[2 3 4]
[1 3]


## 다차원 배열 슬라이싱 (slicing)
* 배열[a:b, c:d]를 이용하여 배열의 일부를 잘라 표시할 수 있음
* 동일하게 배열[a:b:e, c:d:f]를 이용하여 e와 f를 간격으로 사용할 수 있음
* a ~ b는 표시할 행의 위치를 의미하며, c ~ d는 표시할 열의 위치를 의미함

In [26]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print(a, a[:])
print(a___)
print(a___)
print(a___, a___) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]
[1 2] [[1 2]]


## 다차원 배열 슬라이싱 (slicing)
* 배열의 슬라이싱에서 간격만 입력하여 배열을 출력할 수 있음
* [::2, ::2]일 경우, 행을 2칸씩 띄우며, 열도 2칸씩 띄워 출력함

In [27]:
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]])

print(a)
print(a___)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  3  5]
 [11 13 15]]


In [28]:
a, a___, a___, a___

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]), array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]), array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]), array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]))

## 리쉐이프 (Reshape)
* 배열.shape = (행, 열)을 통하여 배열의 형태를 변환할 수 있음
* 행렬의 값은 총 길이의 곱(개수)과 같아야함
* 원본 배열의 크기가 3x4=12일 경우, 리쉐이프 할때 6x2=12로 총 개수와 동일해야함

In [30]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(a)
print(___, ___)  # shape
a.shape = ____  # reshape
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4) (3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## 리쉐이프 (Reshape)
* 3차원 이상의 배열 또한 형태를 변환할 수 있음
* 배열.shape = (페이지, 행, 열)의 순서이며, 역시 총 길이의 개수와 동일해야함

In [32]:
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])

print(a)
print(___, ___)  # shape
a.shape = ___ # reshape
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3) (3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
