## 사칙 연산
* 사칙연산과 관련된 연산은 array와 array 사이에 연산 기호를 포함하여 계산할 수 있음

In [1]:
import numpy as np

a = ......
b = ......

print(a+b)
print(___)
print(___)
print(___)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 기타 연산
* 내적의 경우, np.dot(a, b)를 이용하여 계산할 수 있음
* 이외에도 sin(), cos(), tan(), ceil(), floor(), exp(), mod(), sqrt(), maximum(), minimum()등 다양한 수학 함수도 지원함

In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.ones(3, dtype=int)
c = np.ones((3,3), dtype=int)

print(....)
print(....)

[ 6 15 24]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


## 매트릭스(Metrix) 연산
* array * array의 경우, 결과는 각각의 원소에 대한 곱을 반환함
* 행렬의 곱을 반환해야하는 경우, mat 형식으로 변환 후, 곱 연산을 실행함

In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 3], [2, 4]])

print(a*b)
ma = ....
print(type(a), type(ma))
mb = ....
print(type(a), type(ma))
print(ma*mb)

[[ 1  6]
 [ 6 16]]
<class 'numpy.ndarray'> <class 'numpy.matrix'>
<class 'numpy.ndarray'> <class 'numpy.matrix'>
[[ 5 11]
 [11 25]]


## 매트릭스 클래스
* mat(배열).T의 경우, 매트릭스의 전치값을 반환함
* mat(배열).A의 경우, 매트릭스 형식을 다시 array 형식으로 변환하여 반환함

In [10]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 3], [2, 4]])

ma = ....
mb = ....

print(ma)
print(mb)
print(type(ma), type(mb))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
<class 'numpy.matrix'> <class 'numpy.ndarray'>


## 차원 확장
* index 중 np.newaxis를 이용하여 차원을 확장할 수 있음
* 행 부분에 np.newaxis를 입력시, 차원을 한 단계 추가함
* 열 부분에 np.newaxis를 입력시, 차원을 분해한 후 한 단계 추가함

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a)
print(a___)
print(a___)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


## 차원 확장
* 배열[:, :, :, ... , np.newaxis]를 이용하여 차원을 확장시킬 수 있음
* 차원이 증가함에 따라 index의 표시법이 같이 증가함
* 주로, 슬라이싱를 통한 연산에 사용됨

In [9]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=int)
print(a)
print('\n')

b = a[np.newaxis, :]
print(b)
print('\n')

b = a[np.newaxis, :, :]
print(b)
print('\n')

[[1 2]
 [3 4]
 [5 6]]


[[[1 2]
  [3 4]
  [5 6]]]


[[[1 2]
  [3 4]
  [5 6]]]




In [13]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=int)

b = a[:, np.newaxis]
print(b)
print('\n')

b = a[:, :, np.newaxis]
print(b)
print('\n')

[[[1 2]]

 [[3 4]]

 [[5 6]]]


[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]




In [11]:
b = a[np.newaxis, 0]
print(b)
print('\n')

b = a[0, np.newaxis]
print(b)
print('\n')

b = .....
print(b)
print('\n')

[[1 2]]


[[1 2]]


[[1]
 [2]]




In [12]:
b = a[np.newaxis, 0:2]
print(b)
print('\n')

b = a[0:2, np.newaxis]
print(b)
print('\n')

b = .....
print(b)
print('\n')

[[[1 2]
  [3 4]]]


[[[1 2]]

 [[3 4]]]


[[[1]
  [2]]

 [[3]
  [4]]]




## 차원 확장
* 차원을 어떻게 나누느냐에 따라, 결과가 상이하게 달라짐
* 주로, 배열[:, np.newaxis] 형태로 계산을 진행함

In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print(a[np.newaxis] * b)
print(a[:, np.newaxis] * b)
print("\n")
print(a[np.newaxis] + b)
print(a[:, np.newaxis] + b)

[[1 4 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


[[2 4 6]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 병합
* numpy.hstack([배열1, 배열2])를 이용하여 배열1 우측에 배열2를 이어 붙일 수 있음
* numpy.vstack([배열1, 배열2])를 이용하여 배열1 하단에 배열2를 이어 붙일 수 있음

In [21]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = _____([a, b])
d = _____([a, b])

print(a)
print(b)
print('-'*20)
print(c)
print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
--------------------
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 병합
* numpy.stack([배열1, 배열2, axis=축])를 이용하여 지정한 축으로 배열1과 배열2를 이어 붙일 수 있음
* 축은 이어 붙일 차원의 범위를 넘어갈 수 없음

In [22]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = .....
d = .....

print(a)
print(b)
print('-'*20)
print(c)
print('-'*20)
print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
--------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## 병합
* numpy.dstack([배열1, 배열2])를 이용하여 새로운 축으로 배열1과 배열2를 이어 붙일 수 있음
* numpy.stack([a, b], axis=2)과 동일한 결과를 반환함

In [23]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = .....

print(a)
print(b)
print('-'*20)
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
--------------------
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 병합
* numpy.tile(배열, 반복 횟수)를 이용하여 배열을 반복 횟수만큼 이어 붙일 수 있음

In [24]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = .....

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 특수 병합 메소드
* numpy.c_[배열1, 배열2]를 이용하여 배열1 우측에 배열2를 이어 붙일 수 있음
* numpy.r_[배열1, 배열2]를 이용하여 배열1 하단에 배열2를 이어 붙일 수 있음
* 소괄호 ()를 사용하지 않고 대괄호 []를 사용하여 메소드를 생성함

In [25]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = .....
d = .....

print(c)
print(d)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
